### ISSUE TITLE
Installation EFA Project (MailScanner/Spamassassin)

### ISSUE THREAD

**Issue by comprofix** [JonathanThorpe/spamassassin-vba-macro#1]
Can you please provide some extra instuctions.

I am trying to install this plugin so I can test in an environment before putting into production but I am having issues getting it to work.

I am running a the EFA Project (http://efa-project.org) Mail Filter which users MailScanner/SpamAssassin.

Any help would be appreciated.

Thanks.

**Comment by JonathanThorpe** [comment]
Hi,

If you're running a regular SpamAssasin installation, simply copy the ole2marco.pm file to /etc/spamassassin (or wherever you've installed SpamAssassin) and add the following to your config file

```
loadplugin OLE2Macro ole2macro.pm

body MICROSOFT_OLE2MACRO eval:check_microsoft_ole2macro()
describe MICROSOFT_OLE2MACRO Has an attachment that contains an OLE2 Macro
score MICROSOFT_OLE2MACRO 4
```

Hope this helps!
