### ISSUE TITLE
dbg call not working

### ISSUE THREAD

**Issue by itsbo** [JonathanThorpe/spamassassin-vba-macro#6]
Hi,

depending on where you install the perl module, the logging function is not found:

```
Feb 24 13:45:13 xxx amavis[58394]: (58394-17) _WARN: rules: failed to run MICROSOFT_OLE2MACRO test, skipping:\n\t(Undefined subroutine &OLE2Macro::dbg called at /var/lib/spamassassin/local/ole2macro.pm line 114.\n)
```

The normal spamassassin modules seem to use 

```
use Mail::SpamAssassin::Logger;
```

in order to make this work. I have added this locally in my copy but haven't had time to provoke a call to dbg yet.

**Comment by meschansky** [comment]
@itsbo thanks for pointing this out, my fault. Tested it, now works. Made PR https://github.com/JonathanThorpe/spamassassin-vba-macro/pull/7

**Comment by JonathanThorpe** [comment]
Already fixed in the "fixes" branch.
