### ISSUE TITLE
Check fails on invalid ZIPs

### ISSUE THREAD

**Issue by itsbo** [JonathanThorpe/spamassassin-vba-macro#9]
Hi,

I'm putting this in a separate issue. We sometimes get this error:

```
Mar  2 01:45:11 xxx amavis[20122]: (20122-01) _WARN: rules: failed to run MICROSOFT_OLE2MACRO test, skipping:\n\t(Can't use an undefined value as a HASH reference at /var/lib/spamassassin/local/ole2macro.pm line 131.\n)
```

I am guessing this is due to files that are invalid ZIPs, like this one (from the example above):

```
Mar  2 01:45:10 xxx amavis[20122]: (20122-01) p.path user@example.com: "P=p003,L=1,M=multipart/mixed | P=p002,L=1/2,M=application/octet-stream,T=empty,N=29.02.2016 Rechtsanwalt GiroPay24 AG.zip"
```

Note the the type of the file is detected as "empty" by amavis. According to 

```
http://perldoc.perl.org/IO/Uncompress/Unzip.html 
```

Unzip returns an "undef" if it fails:

```
Returns an IO::Uncompress::Unzip object on success and undef on failure.
```

so you should probably check $z differently (if my spurious knowledge of perl is correct (sorry if otherwise)):

```
--- ole2macro.pm    2016-02-26 10:09:24.290282468 +0100
+++ /var/lib/spamassassin/local/ole2macro.pm    2016-02-26 10:04:42.643100598 +0100
@@ -126,7 +126,7 @@
           my $status;
           my $buff;

-          if ($z) {
+          if (defined $z) {
              for ($status = 1; $status > 0; $status = $z->nextStream()) {
                 if (lc $z->getHeaderInfo()->{Name} =~ $match_types) {
                     $processed_files_counter += 1;`
```

I added this locally and am observing if it persists.

**Comment by itsbo** [comment]
If I send an empty file called file.zip (size=0) apparently a `valid IO::Uncompress::Unzip` object is returned as `(defined $z)` seems to return `true`, _but_ `$z->getHeaderInfo()` returns `undef`. But If I try to catch that with

```
if (defined $z->getHeaderInfo()){
```

I get 

```
Mar  2 14:11:15 xxx amavis[25099]: (25099-03) _WARN: rules: failed to run MICROSOFT_OLE2MACRO test, skipping:\n\t(Can't call method "reset" on an undefined value at /usr/lib/perl5/5.18.1/IO/Uncompress/Base.pm line 986.\n)
```

No idea what I did wrong.

**Comment by JonathanThorpe** [comment]
Thank you very much for finding these bugs. I'll work on them over the next few days.

**Comment by itsbo** [comment]
You are welcome and thank _you_ for all your efforts in fixing these bugs and extending the functionality.
